// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/gen.ts";
import * as $3 from "./routes/greet/[name].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/FieldSelect.tsx";
import * as $$1 from "./islands/Generator.tsx";
import * as $$2 from "./islands/IdeaBox.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/gen.ts": $2,
    "./routes/greet/[name].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/FieldSelect.tsx": $$0,
    "./islands/Generator.tsx": $$1,
    "./islands/IdeaBox.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
