// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/gen.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/xindex.tsx";
import * as $$0 from "./islands/Client.tsx";
import * as $$1 from "./islands/Examples.tsx";
import * as $$2 from "./islands/FieldSelect.tsx";
import * as $$3 from "./islands/Generator.tsx";
import * as $$4 from "./islands/IdeaBox.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/gen.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/xindex.tsx": $5,
  },
  islands: {
    "./islands/Client.tsx": $$0,
    "./islands/Examples.tsx": $$1,
    "./islands/FieldSelect.tsx": $$2,
    "./islands/Generator.tsx": $$3,
    "./islands/IdeaBox.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
