import { PageProps } from "$fresh/server.ts";
import { Head } from "$fresh/runtime.ts";
import Body from "../components/Body.tsx";

import { Handlers } from "$fresh/server.ts";

const delimiter = "-project-ideas";

export const handler: Handlers = {
  async GET(_req, ctx) {
    const { slug } = ctx.params;

    const regex = new RegExp(delimiter);

    const skill = slug.split(regex)[0]?.replaceAll("-", " ");

    const isPathCorrectPattern = /([a-z]+)-project-ideas/.test(slug);

    if (!skill || !isPathCorrectPattern) {
      return new Response("", {
        status: 307,
        headers: { Location: "/" },
      });
    }

    const title = `${skill} project ideas`;

    const resp = await ctx.render({
      title,
      skill,
    });

    return resp;
  },
};

export default function Post(props: PageProps) {
  const { title, skill } = props.data;

  return (
    <>
      <Head>
        <title>
          {title}
          <meta
            name="description"
            content={`
            ${title} generated by AI. For makers who want to work on something new.`}
          />
        </title>
      </Head>
      {/* TODO: may you consider a better way to prop drill the skill tag. */}
      <Body slug={skill} />
    </>
  );
}
