import { Head } from "$fresh/runtime.ts";

import Generator from "../islands/Generator.tsx";
import Header from "../components/Header.tsx";
import Footer from "../components/Footer.tsx";
import Examples from "../islands/Examples.tsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kanalize | Open Source Idea Generator Powered by OpenAI</title>
        <meta
          name="description"
          content="Kanalize is a simple tool to generate open-source project ideas for developers. It's a tool that you can use when you're bored and want to work on something new. "
        />
        <meta name="twitter:site" content="@furkaneulogy" />
        <meta name="twitter:creator" content="@furkaneulogy" />
        <meta
          name="twitter:title"
          content="Open Source Project ideas powered by AI"
        />
        <meta
          name="twitter:description"
          content="Open source project ideas generated by AI. For developers who want to work on something new."
        />
        {
          /* <meta
          name="twitter:image:src"
          content=""
        /> */
        }
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Open Source Project ideas by AI" />
        {
          /* <meta
          property="og:image"
          content=""
        /> */
        }
        <meta
          property="og:description"
          content="Open source project ideas generated by AI. For developers who want to work on something new."
        />
        <meta property="og:url" content="https://ossideaai.com/" />
        <meta name="twitter:url" content="https://ossideaai.com/" />
        <meta name="robots" content="index, follow" />
      </Head>

      <main className="min-h-screen bg-gray-200 w-full md:px-0 px-8">
        <div className="container mx-auto py-4 gap-4 px-0 md:px-20 min-h-screen">
          <Header />
          <Generator />
          <Examples />
        </div>
        <div className="container mx-auto py-4 gap-4 px-0 md:px-20 ">
          <Footer />
        </div>
      </main>
    </>
  );
}
