import { Head } from "$fresh/runtime.ts";

import Body from "../components/Body.tsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Open Source Project ideas powered by AI
        </title>
        <meta
          name="description"
          content="Kanalize is a simple tool to generate open-source project ideas for developers. It's a tool that you can use when you're bored and want to work on something new. "
        />
        <meta name="twitter:site" content="@furkaneulogy" />
        <meta name="twitter:creator" content="@furkaneulogy" />
        <meta
          name="twitter:title"
          content="Open Source Project ideas powered by AI"
        />
        <meta
          name="twitter:description"
          content="Open source project ideas generated by AI. For developers who want to work on something new."
        />
        {
          /* <meta
          name="twitter:image:src"
          content=""
        /> */
        }
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Open Source Project ideas by AI" />
        {
          /* <meta
          property="og:image"
          content=""
        /> */
        }
        <meta
          property="og:description"
          content="Open source project ideas generated by AI. For developers who want to work on something new."
        />
        <meta property="og:url" content="https://ossideaai.com/" />
        <meta name="twitter:url" content="https://ossideaai.com/" />
        <meta name="robots" content="index, follow" />
      </Head>
      <Body />
    </>
  );
}
