export const sectors = [
  "Health and fitness",
  "Education and learning",
  "Online shopping",
  "Home gardening",
  "Clean energy at home",
  "AI assistance",
  "Virtual reality experiences",
  "Smartphone apps",
  "Public transportation",
  "Exercise and wellness",
  "Mobile games",
  "Music and video streaming",
  "Green living",
  "Food delivery services",
  "Travel and vacations",
  "Home improvement",
  "Financial tools",
  "Environmental protection",
  "products",
  "Safe drinking water",
  "Home entertainment",
  "Movies and TV shows",
  "Renewable energy sources",
  "Electric vehicles",
  "Home automation",
  "3D printing technology",
  "Digital currencies",
  "Online security",
  "Smart home devices",
  "City planning",
  "Healthy food options",
  "Telehealth services",
  "Stress relief and relaxation",
  "Language learning apps",
  "Senior citizen care",
  "Childcare solutions",
  "Online marketplaces",
  "Drone technology",
  "Medical advancements",
  "Sustainable packaging",
  "Organic farming",
  "building materials",
  "Investing for impact",
  "Green energy advice",
  "Wearable gadgets",
  "Mobile payments",
  "Space tourism",
  "Electric bicycles",
  "Personalized nutrition plans",
  "Health tracking devices",
  "cleaning products",
  "Zero-waste living",
  "Smart farming practices",
  "Energy storage solutions",
  "AI-powered content creation",
  "Online education tools",
  "Forestry and conservation",
  "Clean water solutions",
  "Disaster preparedness",
  "Virtual events and meetings",
  "Remote work solutions",
  "Sustainable architecture",
  "Electric boats",
  "Personal safety gadgets",
  "Green transportation options",
  "Fashion and accessories",
  "Renewable energy education",
  "events",
  "Fresh and sustainable seafood",
  "Efficient waste management",
  "Personalized health plans",
  "Clean transportation",
  "Advocating for renewable energy policies",
  "Teaching green practices",
  "Pet care and products",
];
