const skills = [
  "javascript",
  "react",
  "python",
  "java",
  "c++",
  "node.js",
  "sql",
  "git",
  "html5",
  "css3",
  "ruby on rails",
  "php",
  "swift",
  "go",
  "vue.js",
  "angular",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "restful apis",
  "graphql",
  "microservices",
  "testing (junit, pytest, jasmine)",
  "continuous integration/continuous deployment (ci/cd)",
  "agile development",
  "scrum",
  "devops",
  "algorithms",
  "data structures",
  "machine learning",
  "artificial intelligence",
  "natural language processing",
  "big data",
  "blockchain technology",
  "web security",
  "code optimization",
  "debugging",
  "backend development",
  "frontend development",
  "full stack development",
  "mobile app development",
  "version control",
  "responsive design",
  "shell scripting",
  "object-oriented programming (oop)",
  "functional programming",
  "software architecture",
  "ui/ux design",
  "rest api design",
  "database design",
  "linux/unix",
  "containerization",
  "rust",
  "typescript",
];

export default skills;
